// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcTiggy.Models;

namespace MvcTiggy.Migrations
{
    [DbContext(typeof(MvcAdventureContext))]
    partial class MvcAdventureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("MvcTiggy.Models.Adventure", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("Duration");

                    b.Property<int>("DurationUnits");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte[]>("Image");

                    b.Property<string>("Name");

                    b.Property<DateTime>("PlannedDate");

                    b.HasKey("ID");

                    b.ToTable("Adventure");
                });

            modelBuilder.Entity("MvcTiggy.Models.AdventureMember", b =>
                {
                    b.Property<int>("AdventureId");

                    b.Property<int>("MemberId");

                    b.HasKey("AdventureId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("AdventureMember");
                });

            modelBuilder.Entity("MvcTiggy.Models.Member", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<string>("FirstName");

                    b.Property<byte[]>("Image");

                    b.Property<string>("LastName");

                    b.HasKey("ID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MvcTiggy.Models.AdventureMember", b =>
                {
                    b.HasOne("MvcTiggy.Models.Adventure", "Adventure")
                        .WithMany("AdventureMembers")
                        .HasForeignKey("AdventureId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MvcTiggy.Models.Member", "Member")
                        .WithMany("AdventureMembers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
